-- MySQL Script generated by MySQL Workbench
-- 08/27/16 11:18:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema odontotech_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema odontotech_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `odontotech_bd` set utf8 collate utf8_general_ci;
USE `odontotech_bd` ;

-- -----------------------------------------------------
-- Table `odontotech_bd`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(250) NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(250) NULL,
  `dt_nascimento` DATE NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `nivel_acesso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoa`))
collate 'utf8_general_ci';


-- -----------------------------------------------------
-- Table `odontotech_bd`.`dentista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`dentista` (
  `id_dentista` INT NOT NULL AUTO_INCREMENT,
  `cro` VARCHAR(45) NOT NULL,
  `especializacao` VARCHAR(250) NOT NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_dentista`, `pessoa_id_pessoa`),
  INDEX `fk_dentista_pessoa_idx` (`pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_dentista_pessoa`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `odontotech_bd`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
collate 'utf8_general_ci';


-- -----------------------------------------------------
-- Table `odontotech_bd`.`logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`logradouro` (
  `id_logradouro` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(250) NOT NULL,
  `bairro` VARCHAR(250) NOT NULL,
  `complemento` VARCHAR(250) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_logradouro`))
collate 'utf8_general_ci';


-- -----------------------------------------------------
-- Table `odontotech_bd`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`paciente` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `nacionalidade` VARCHAR(150) NOT NULL,
  `est_civil` VARCHAR(45) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `local_nascimento` VARCHAR(250) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `profissao` VARCHAR(250) NOT NULL,
  `responsavel` VARCHAR(250) NOT NULL,
  `tel_responsavel` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(250) NULL,
  `bairro` VARCHAR(250) NULL,
  `complemento` VARCHAR(200) NULL,
  `cidade` VARCHAR(100) NULL,
  `numero` VARCHAR(100) NULL,
  `nm_residencial` VARCHAR(10) NULL,
  `pessoa_id` INT NOT NULL,
  `logradouro_id_logradouro` INT NOT NULL,
  PRIMARY KEY (`id_paciente`, `pessoa_id`, `logradouro_id_logradouro`),
  INDEX `fk_paciente_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_paciente_logradouro1_idx` (`logradouro_id_logradouro` ASC),
  CONSTRAINT `fk_paciente_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `odontotech_bd`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_logradouro1`
    FOREIGN KEY (`logradouro_id_logradouro`)
    REFERENCES `odontotech_bd`.`logradouro` (`id_logradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
collate 'utf8_general_ci';


-- -----------------------------------------------------
-- Table `odontotech_bd`.`protuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`protuario` (
  `id_prontuario` INT NOT NULL AUTO_INCREMENT,
  `dt_cadastro` DATE NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_prontuario`, `paciente_id_paciente`),
  INDEX `fk_protuario_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_protuario_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `odontotech_bd`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
collate 'utf8_general_ci';


-- -----------------------------------------------------
-- Table `odontotech_bd`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`anamnese` (
  `id_anamnese` INT NOT NULL AUTO_INCREMENT,
  `questao_1` VARCHAR(250) NOT NULL,
  `questao_2` VARCHAR(250) NOT NULL,
  `questao_3` VARCHAR(250) NOT NULL,
  `questao_4` VARCHAR(250) NOT NULL,
  `questao_5` VARCHAR(250) NOT NULL,
  `questao_6` VARCHAR(250) NOT NULL,
  `questao_7` VARCHAR(250) NOT NULL,
  `info_add` VARCHAR(250) NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_anamnese`, `paciente_id_paciente`),
  INDEX `fk_anamnese_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_anamnese_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `odontotech_bd`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
collate 'utf8_general_ci';


-- -----------------------------------------------------
-- Table `odontotech_bd`.`procedimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`procedimento` (
  `id_procedimento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(150) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `protuario_id_prontuario` INT NOT NULL,
  PRIMARY KEY (`id_procedimento`, `protuario_id_prontuario`),
  INDEX `fk_procedimento_protuario1_idx` (`protuario_id_prontuario` ASC),
  CONSTRAINT `fk_procedimento_protuario1`
    FOREIGN KEY (`protuario_id_prontuario`)
    REFERENCES `odontotech_bd`.`protuario` (`id_prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
collate 'utf8_general_ci';


-- -----------------------------------------------------
-- Table `odontotech_bd`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`receita` (
  `id_receita` INT NOT NULL AUTO_INCREMENT,
  `desconto` DOUBLE NOT NULL,
  `dt_pagamento` DATE NOT NULL,
  `procedimento_id_procedimento` INT NOT NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_receita`, `procedimento_id_procedimento`, `pessoa_id_pessoa`),
  INDEX `fk_receita_procedimento1_idx` (`procedimento_id_procedimento` ASC),
  INDEX `fk_receita_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_receita_procedimento1`
    FOREIGN KEY (`procedimento_id_procedimento`)
    REFERENCES `odontotech_bd`.`procedimento` (`id_procedimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `odontotech_bd`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
collate 'utf8_general_ci';

-- -----------------------------------------------------
-- Table `odontotech_bd`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontotech_bd`.`agenda` (
  `id_agenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `procedimento_id` INT NOT NULL,
  `dentista_id_dentista` INT NOT NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_agenda`, `procedimento_id`, `dentista_id_dentista`, `pessoa_id_pessoa`),
  INDEX `fk_agenda_procedimento1_idx` (`procedimento_id` ASC),
  INDEX `fk_agenda_dentista1_idx` (`dentista_id_dentista` ASC),
  INDEX `fk_agenda_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_agenda_procedimento1`
    FOREIGN KEY (`procedimento_id`)
    REFERENCES `odontotech_bd`.`procedimento` (`id_procedimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_dentista1`
    FOREIGN KEY (`dentista_id_dentista`)
    REFERENCES `odontotech_bd`.`dentista` (`id_dentista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `odontotech_bd`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
collate 'utf8_general_ci';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
